### ISSUE TITLE
Investigate ell

### ISSUE THREAD

**Issue by ErikBjare** [ErikBjare/gptme#127]
Looks really nice: https://docs.ell.so/core_concepts/ell_complex.html

Not sure if a good fit for gptme though, but looks very similar in approach.

**Comment by ErikBjare** [comment]
More intrigued by simplemind: https://github.com/ErikBjare/gptme/issues/233

**Comment by lingster** [comment]
For what it's worth, I quite like ell, as it stores version history of your prompts so you can later review and replay them. Can help with prompt optimisation. Is multi modal too.

**Comment by ErikBjare** [comment]
Might try it later, but no point keeping this open.

@lingster Thanks for sharing your experience with it :)
