### ISSUE TITLE
Doesn't work with DeepSeek: `UnprocessableEntityError: Failed to deserialize the JSON body into the target type`

### ISSUE THREAD

**Issue by brucevoin** [ErikBjare/gptme#170]
File "/home/brucevoin/.local/share/pipx/venvs/gptme/lib/python3.12/site-packages/openai/_base_client.py", line 1052, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Failed to deserialize the JSON body into the target type: messages[3]: invalid type: sequence, expected a string at line 1 column 27074

**Comment by ErikBjare** [comment]
Huh, I've never seen this before. What triggered it for you?

**Comment by brucevoin** [comment]
> Huh, I've never seen this before. What triggered it for you?

Maybe the reason is I used deepseek api.

**Comment by ErikBjare** [comment]
Probably, I will investigate.

**Comment by ErikBjare** [comment]
Managed to reproduce, looks like it doesn't support how we/openai/anthropic deal with message attachments like files/images: https://github.com/clinebot/cline/issues/230

I could work around this, but I'd rather wait for them to fix their API.

**Comment by ErikBjare** [comment]
I started working on proper support for DeepSeek in https://github.com/ErikBjare/gptme/pull/180

**Comment by ErikBjare** [comment]
Same issue for groq apparently, working on a fix in: https://github.com/ErikBjare/gptme/pull/231

**Comment by ErikBjare** [comment]
Fixed in #180
