### ISSUE TITLE
whitelist some commands

### ISSUE THREAD

**Issue by brayo-pip** [ErikBjare/gptme#183]
Should not need user interaction to run commands such as `ls` `stat` `cd`. Some such as `cat` can also be whitelisted for anything that is not .env .key etc.  Not sure what would work best yet, a regex?

**Comment by ErikBjare** [comment]
Nice idea, but I'm not sure if it's confusing to users why its running commands without asking.

> Not sure what would work best yet, a regex?

Just do:

```py
code = code.strip()
single_cmd = code.count("\n")   # not quite right, but good enough? (doesn't detect compount statements using `;`)
is_safe_cmd = any(code.startswith(safe_cmd) for safe_cmd in ['ls', 'stat', 'cd', 'cat'])
if single_cmd and is_safe_cmd:
    # skip check
```

**Comment by ErikBjare** [comment]
I refactored how confirmation prompts work in https://github.com/ErikBjare/gptme/pull/199

We now pass down a `ConfirmFunc` which takes a message and returns a bool. It makes it possible to not only prompt the user for confirmation, but also allowlist rules, ask an LLM to confirm, ask the user for confirmation in the web UI/REST API, or just return True to skip confirmation.

**Comment by 0xbrayo** [comment]
My laptop is not working right now. Should be fixed by Thursday. But I'll
try to get this done tonight though.

**Comment by 0xbrayo** [comment]
Completed in #190
