### ISSUE TITLE
No tools work with Llama 1B

### ISSUE THREAD

**Issue by PtasiaDupka** [ErikBjare/gptme#195]
I did everything as said in the documentation but tools just don't execute. For example, if I type "write a snake game to snake.py", the LLM does its job and writes the code but gptme doesn't write it to the file. No messagies from "System", just "User:" prompt again.

**Comment by PtasiaDupka** [comment]
Looks like the LLM should be taught how to form output the way gptme understands it, but how? I didn't find any commands for that

**Comment by PtasiaDupka** [comment]
Okay, I looked into the code and figured out the llm is given all the information it needs to act as intended at the very beginning of every conversation. 

I ran gptme with --show-hidden and then just in case also checked the file where the conversation history is stored. Gptme does instruct llm but it just ignores it...

I also forgot to mention that I'm using llama3.2:1b just as in the example from the docs.

**Comment by ErikBjare** [comment]
Llama 1B is nowhere near good enough to adhere to the system prompt. It is merely an example in the docs for how to get the most minimal setup done.

Llama 70B and up behave somewhat correctly (with 405B being really good). 

Check the evals to see which models actually work: https://gptme.org/docs/evals.html
