### ISSUE TITLE
what is difference between gptme and open-interpreter ? 

### ISSUE THREAD

**Issue by CoderYiFei** [ErikBjare/gptme#204]
what is difference between gptme and open-interpreter ?

**Comment by ErikBjare** [comment]
That's a great question. I haven't kept up with open-interpreter, so I really cannot say what their direction/focus is.

I've been meaning to make a review of alternatives/similar tools and put it in the docs (see https://github.com/ErikBjare/gptme/issues/112), but I've been putting it off for reasons (I want to be fair, takes effort to evaluate). We can continue the discussion in that issue.

I would love to hear people's experiences about how they think gptme compares to other tools.
