### ISSUE TITLE
Groq openai.BadRequestError:

### ISSUE THREAD

**Issue by arieltoledo** [ErikBjare/gptme#227]
Hi everybody, Im trying to use gtpme with groq models but after the firts command the program halts with  
openai.BadRequestError: Error code: 400 - {'error': {'message': "'messages.2' : for 'role:assistant' the following must be satisfied[('messages.2.content' : value must be a string)]", 'type': 'invalid_request_error'}}.
Help appreciatte.

**Comment by 0xbrayo** [comment]
Is it only happening with groq models?

**Comment by ErikBjare** [comment]
Sorry about that, looks like I tested it a bit too hastily. Will fix this tomorrow.

**Comment by ErikBjare** [comment]
Didn't end up waiting until tomorrow. Fixed in https://github.com/ErikBjare/gptme/pull/231

Had the side effect of also fixing Deepseek support (https://github.com/ErikBjare/gptme/issues/170), which is now also supported on the master branch.

A new release will be out soon.

Thanks for reporting!

**Comment by arieltoledo** [comment]
Great, thanks. The tools is amazing

**Comment by aborruso** [comment]
Thank you very much @ErikBjare  !!
