### ISSUE TITLE
cannot run browser tool

### ISSUE THREAD

**Issue by ibagur** [ErikBjare/gptme#228]
I have followed the instructions and installed gptme on macos 14.6.1 as per:

```
pipx install gptme[browser]
gptme '/shell playwright install chromium'
```

The default model used is `claude-3-5-sonnet-20241022` (latest). However when trying to run the example `gptme 'find out which is the latest ActivityWatch version from superuserlabs.org'`, I get the following error:

```
WARNING:gptme.chat:Failed to read URL http://www....BrowserType.launch: Executable doesn't exist at /Users/inigo/Library/Caches/ms-playwright/chromium-1134/chrome-mac/Chromium.app/Contents/MacOS/Chromium
```

I checked the directory and apparently Chromium is installed, but there is a discrepancy in the directory path, as the installation  is 1140 instead of 1134:

```
/Users/inigo/Library/Caches/ms-playwright/chromium-1140/...
```

Any suggestions on how to proceed?

Thanks!

UPDATE: I manually changed the directory name under `.../ms-playwright/´from `chromium-1140` to `chromium-1134` and now it's fine. A bit dirty but it worked.

**Comment by ErikBjare** [comment]
Weird.

I get the error whenever updating playwright, but doing a `playwright install` with the right version of playwright fixes it. I thought `gptme '/shell playwright install chromium'` would always use the same playwright version as the one in the venv used by gptme, but I guess not?

Side-note: I'm kinda tired of Playwright, as its a bit overkill for most browsing, so I've investigated adding lynx support instead, which is a lot faster, cleaner output, and more lightweight (but less capable): https://github.com/ErikBjare/gptme/issues/205

Glad you found a workaround!
