### ISSUE TITLE
Investigate simplemind

### ISSUE THREAD

**Issue by ErikBjare** [ErikBjare/gptme#233]
@kennethreitz new project: https://pypi.org/project/simplemind/

**Comment by 0xbrayo** [comment]
@ErikBjare I want to try this out. Should I make a draft PR replacing the `langchain` with `simplemind`?.

**Comment by ErikBjare** [comment]
We don't have any langchain (thankfully), but feel free to experiment.

I don't think we'll merge something like it anytime soon though, too big a refactor and I don't see an obvious benefit, yet.

**Comment by 0xbrayo** [comment]
I thought I saw langchain here... Must have been somewhere else

**Comment by 0xbrayo** [comment]
It's in a scripts folder. my bad
