### ISSUE TITLE
Building Bob the Builder - the first gptme agent

### ISSUE THREAD

**Issue by ErikBjare** [ErikBjare/gptme#259]
Private repo for now, but promising results!

Announcing Bob: https://x.com/ErikBjare/status/1857418334913933717
Repo (private): https://github.com/ErikBjare/gptme-bob

He built this by himself: https://github.com/ErikBjare/gptme-rag

**Comment by ErikBjare** [comment]
I asked @brayo-pip to play with his own version of it, curious to see how it goes.

**Comment by danielw97** [comment]
This sounds like an interesting approach, looking forward to experimenting with this at some point when it is made public.
I'm using gptme daily, and the capabilities are already extremely helpful.

**Comment by ErikBjare** [comment]
@danielw97 That's great to hear! Would love to hear any feedback you might have in the [discussions](https://github.com/ErikBjare/gptme/discussions).

**Comment by ErikBjare** [comment]
I just published [gptme-agent-template](https://github.com/ErikBjare/gptme-agent-template) which can be used to fork new agents, the template itself is forked from Bob.

Announcement: https://x.com/ErikBjare/status/1859544004628500649

**Comment by danielw97** [comment]
This agent strategy looks very interesting, I'm going to check the template out.
Are you planning to make any agents open source in the future alongside the basic template?
I completely understand if not as they are probably streamlined for specific tasks, and the template is a very cool concept in and of itself.
I know you mentioned that the bob repo whilst the link is included is private currently.
Thanks again for all of your work on this!

**Comment by ErikBjare** [comment]
@danielw97 I'm mostly playing with Bob in private right now to dogfood it and figure out how to improve the harness.

My plan is to update the agent template with my improvements regularly, and work on tools and systems in gptme to further empower the agents' capabilities (currently focused on RAG & email).

**Comment by danielw97** [comment]
Makes total sense to me, I'm starting to experiment with the template and can give some feedback depending on how I get on over on that repo if it's helpful.

**Comment by ErikBjare** [comment]
@danielw97 I would love that!

**Comment by 0xbrayo** [comment]
Built an ActivityWatch [agent](https://github.com/brayo-pip/aw-gpt), will use it this week and see just how much it can achieve. Been helpful in fixing the failing tests today on `aw-tauri`.

**Comment by ErikBjare** [comment]
Bob now has a GitHub account: @TimeToBuildBob

I've now updated the agent template significantly, we will track work on gptme agents in the template repo instead of this lone issue.
