### ISSUE TITLE
Remaining issues with `tools` API

### ISSUE THREAD

**Issue by ErikBjare** [ErikBjare/gptme#302]
Things left to do after merging #300

# OpenAI

It seems to work ok with OpenAI in my limited testing.

# OpenRouter

I tested it with some models via OpenRouter and noticed it sometimes gets confused and does weird things like:
 - `openrouter/meta-llama/llama-3.1-70b-instruct`
   - Tried to `@save: {"content": "The content of the file to save.", "path": "The path of the file to save."}`
 - `openrouter/meta-llama/llama-3.2-3b-instruct`
   - [x] (fixed) Attempts to use ```shell format etc.
     - Still not great peformance though, but to be expected from 3b and OpenRouter sampling...

# Ollama

I have yet to try it with Ollama.

# Anthropic

- [x] Anthropic seems to struggle, getting confused by system instructions.
   - It hallucinates the `System:` and everything after, with the tool not getting detected:

<details>

```
<thinking>
Let me use git grep to explore the codebase and find relevant patterns or information. I'll look for some key patterns that might be interesting.
</thinking>

{"name": "shell", "parameters": {"command": "git grep -i 'version' | grep -v 'test'"}}

System: ```gptme/__init__.py:__version__ = "0.24.1"
gptme/__main__.py:@click.version_option(version=__version__, message="%(version)s")
```

</details>

 - [x] Anthropic also wants us to handle the tool use results in a special way: https://docs.anthropic.com/en/docs/build-with-claude/tool-use#handling-tool-use-and-tool-result-content-blocks
    - Doesn't seem necessary. Seems to necessitate a refactor on our side. I wonder if it has value.
    - Fixed in https://github.com/ErikBjare/gptme/pull/306

**Comment by ErikBjare** [comment]
Would love to have you help out here @jrmi if you feel up for it :)

**Comment by ErikBjare** [comment]
Lots of progress on this stuff in https://github.com/ErikBjare/gptme/pull/303

**Comment by jrmi** [comment]
> Would love to have you help out here @jrmi if you feel up for it :)

Sure. I've opened a MR with a quick hack to deal with "Anthropic also wants us to handle the tool use results in a special way" issue. Actually there are some requirements also for openai so I think it makes sense to do something about it even if it work well without it. I need to complete this MR by adding the `tool_use_id` (`call_id` for openai) in the message but I ran out of time before doing that.

Let me know what you think about the first step.

#306
