### ISSUE TITLE
Workspace files should include full path in prompt

### ISSUE THREAD

**Issue by Miyou** [ErikBjare/gptme#329]
Currently `get_workspace_prompt` gives the files from `gptme.toml` with the prefix ```{filename}. It would perhaps be better if it gave the path rather than just the filename, so the LLM is more aware of which file the contents are from. Especially considering files can often have the same name e.g. `README.md`.

**Comment by ErikBjare** [comment]
Fixed in #330

**Comment by Miyou** [comment]
> Fixed in #330

Nice. Just noticed a similar issue that I'm not sure how much of an issue it is. In some of my included markdown files there is code examples using triple backtick, but since the files included in the prompt use triple backtick it becomes unclear when the file ends and when the code example from within the file begins. Perhaps using something other than triple backtick for the files would be better.

**Comment by ErikBjare** [comment]
@Miyou Yeah I use XML-formatting in gptme-rag output for this reason:

```xml
<file path="...">
(content)
</file>
```

Might be worth doing for the context message and such too.
