### ISSUE TITLE
Option to allow for multiple confirms, (but not inifinite)

### ISSUE THREAD

**Issue by FilipHarald** [ErikBjare/gptme#332]
`--no-confirm` is awesome. Although I don't like the thought of leaving the agent running draining all my tokens :) I was thinking it might be good to give it a couple of allowed confirms before requiring user interaction again. Something like this:

```bash
gptme 'make task X which will probably take a lot of iterations' --skip-confirms 10
```

From within the tool perhaps `/skip-confirms 10` would work?

**Comment by ErikBjare** [comment]
Do you know about answering `auto` in the `[Y/n/e/?]` confirmation prompt?

Maybe adding a `auto 5` or `y 5` option to that prompt could work to let it take `n` steps itself before pausing.
