### ISSUE TITLE
-n CLI flag is used for both the "name" as well as "non-interactive" mode

### ISSUE THREAD

**Issue by bjsi** [ErikBjare/gptme#360]
![CleanShot 2024-12-21 at 14 57 32](https://github.com/user-attachments/assets/a8153aec-edf8-46b1-a760-d025c58e3e88)

**Comment by ErikBjare** [comment]
lmao, which should we keep?

**Comment by bjsi** [comment]
I would guess that people don't want to name their conversations that often, I think it would be ok to remove the flag for that

**Comment by ErikBjare** [comment]
Nice find, fixed in https://github.com/ErikBjare/gptme/commit/dd26dc2366739ddfc0eff7fb3e8eb9d4c9535053
