### ISSUE TITLE
patch causes critical failure

### ISSUE THREAD

**Issue by nslieske** [ErikBjare/gptme#39]
running the main branch (love this software by the way, very useful!!)

```patch vkdl.py
@@ -156,5 +156,11 @@
 print("Moving downloaded videos to /media/gdrive/solar/cells/masterclips/")
-shutil.move(f'{output_dir}/*.mp4', '/media/gdrive/solar/cells/masterclips/')
+for file_name in os.listdir(output_dir):
+    if file_name.endswith('.mp4'):
+        shutil.move(os.path.join(output_dir, file_name), '/media/gdrive/solar/cells/masterclips/')
+
 print("Video downloading process completed.")
```                                                         
Applying the patch kills the app.  I'm able to recover by asking to build and save the file.  

Traceback (most recent call last):
  File "/home/noah/.local/bin/gptme", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noah/.local/lib/python3.11/site-packages/gptme/cli.py", line 219, in main
    for msg in loop(log, no_confirm, model, stream=stream):  # pragma: no cover
  File "/home/noah/.local/lib/python3.11/site-packages/gptme/cli.py", line 271, in loop
    yield from execute_msg(msg_response, ask=not no_confirm)
  File "/home/noah/.local/lib/python3.11/site-packages/gptme/tools/__init__.py", line 30, in execute_msg
    yield from execute_codeblock(codeblock, ask)
  File "/home/noah/.local/lib/python3.11/site-packages/gptme/tools/__init__.py", line 46, in execute_codeblock
    yield from execute_patch(f"```{codeblock}```", fn, ask=ask)
  File "/home/noah/.local/lib/python3.11/site-packages/gptme/tools/patch.py", line 95, in execute_patch
    apply_file(codeblock, fn)
  File "/home/noah/.local/lib/python3.11/site-packages/gptme/tools/patch.py", line 71, in apply_file
    assert Path(filename).exists()
AssertionError

**Comment by nslieske** [comment]
I used gptme to find out that it's not modifying the file in the correct path:

```
Assistant: The contents of `/home/noah/crash.txt` indicate that there was an issue when a patch was applied to a file. The traceback shows that the application crashed at the point where it asserts that a file path exists. This suggests that the file it was trying to patch did not exist or was not found.

The patch in the crash log is attempting to change a line of code that moves `.mp4` files from one directory to another. The original line using `shutil.move` with a wildcard pattern was replaced with a loop that iterates over files in a directory and moves each `.mp4` file individually.

The error `AssertionError` at the end of the traceback indicates that the assertion `Path(filename).exists()` failed, which means the file it was trying to patch was not found at the expected location.

To resolve this issue, you would need to ensure that the file you are trying to patch exists and that the path to the file is correct. If the file does exist, you might need to check the permissions to make sure that the script has the necessary access to read and write to the file.

If you have the file that needs to be patched and want to apply the patch manually, you can do so by editing the file to include the new loop for moving `.mp4` files. If you need assistance with that, I can guide you through the process.                                                                                                                                                               User:

**Comment by ErikBjare** [comment]
Ah, yes that should be an easy fix. Thanks for reporting!

**Comment by ErikBjare** [comment]
Fixed now!

However, do note that the ```patch codeblocks are not meant for the actual diff/patch format (since GPTs can't reliably generate them, failing on the line number math). Instead they use a git-conflict-marker like syntax, like this:

````
```patch hello.py
<<<<<<< ORIGINAL
    print("Hello world")
=======
    name = input("What is your name? ")
    print(f"hello {name}")
>>>>>>> UPDATED
```
````
