### ISSUE TITLE
display stdout to screen while executing code - enhancement

### ISSUE THREAD

**Issue by nslieske** [ErikBjare/gptme#40]
While it is executing code, it would be nice to see the stdout of the script as it's happening, so you know it's working properly.

Do you guys want stuff like this here?  I have a bunch of suggestions, but don't want to annoy you. 

Cheers on an excellent piece of software...

**Comment by ErikBjare** [comment]
Yes, that would be great indeed!

If you have a bunch of suggestions, create a new issue and list them all, and I'd be happy to go through them and see what I can do :)

**Comment by nslieske** [comment]
Will do.  On this particular one, I had the idea this morning to have a listener in a split or separate window in tmux or screen, so the stdout goes to that listener, and the primary screen keeps the prompt persistent, while still listens.

I did something like this the other night in tmux, telling gptme to split tmux, ssh into another box, and perform commands in the split window.  It got a little clunky obviously.  So tying together the two ideas, where the separate screen or tmux window would be a listener, would solve both problems.  You could execute code and see the results, as well as navigate machines from the primary terminal, if the secondary, tertiary, etc., terminals were listeners.

I guess this then ties into the other main idea I had of making it auto-gpt like, where those screens could then be additional agents.  I'm sure you've had all these ideas already.

**Comment by ErikBjare** [comment]
Fixed this in https://github.com/ErikBjare/gptme/commit/be40f10c2b9db40c5b677b5277f970eb4f56d39e

Thanks for your comments, interesting ideas about using tmux like that (I'm a big fan/user of tmux). Will think about that a bit more :)

**Comment by nslieske** [comment]
This is great, it works awesome.  Of course first thing I do is try ssh and it can't display a pseudo terminal. I can run remote commands, but that's less than ideal. I know this is expected behavior, but still thinking of a way to have gptme listen while navigating various servers and able to execute into the server that you are currently on. Chatting with gptme gave me the idea of using paramiko to make an interactive ssh shell instead of the tmux idea.  Food for thought.

User: /shell ssh -t dev
Pseudo-terminal will not be allocated because stdin is not a terminal.

Linux core-dev 6.1.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.4-1 (2023-01-07) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.

**Comment by nslieske** [comment]
I fiddled with it for a bit and reached my capacity.  the function works as a standalone python script, but I have no idea if I'm on the right track or not.

import paramiko                                                                                                                                        
import sys                                                                                                                                             
import select                                                                                                                                          
import termios                                                                                                                                         
import tty                                                                                                                                             
                                                                                                                                                       
def interactive_ssh_session(hostname, port, username):                                                                                                 
    # Create an SSH client instance                                                                                                                    
    ssh_client = paramiko.SSHClient()                                                                                                                  
    ssh_client.set_missing_host_key_policy(paramiko.AutoAddPolicy())                                                                                   
                                                                                                                                                       
    # Connect to the remote server                                                                                                                     
    ssh_client.connect(hostname, port=port, username=username)                                                                                         
                                                                                                                                                       
    # Get the transport                                                                                                                                
    transport = ssh_client.get_transport()                                                                                                             
    session = transport.open_session()                                                                                                                 
                                                                                                                                                       
    # Get a pseudo-terminal                                                                                                                            
    session.get_pty()                                                                                                                                  
                                                                                                                                                       
    # Start the shell                                                                                                                                  
    session.invoke_shell()                                                                                                                             
                                                                                                                                                       
    # Save the terminal settings                                                                                                                       
    oldtty = termios.tcgetattr(sys.stdin)                                                                                                              
    try:                                                                                                                                               
        # Put the terminal into raw mode to pass all input directly to the shell                                                                       
        tty.setraw(sys.stdin.fileno())                                                                                                                 
        session.settimeout(None)                                                                                                                       
                                                                                                                                                       
        while True:                                                                                                                                    
            # Wait for data to become available on stdin or the SSH channel                                                                            
            readable, _, _ = select.select([sys.stdin, session], [], [])                                                                               
            if sys.stdin in readable:                                                                                                                  
                # Read from stdin and write to the SSH channel                                                                                         
                input_data = sys.stdin.read(1)                                                                                                         
                session.send(input_data)                                                                                                               
            if session in readable:                                                                                                                    
                # Read from the SSH channel and write to stdout                                                                                        
                output_data = session.recv(256)                                                                                                        
                if len(output_data) == 0:                                                                                                              
                    # End of file, break the loop                                                                                                      
                    break                                                                                                                              
                sys.stdout.write(output_data.decode('utf-8'))                                                                                          
                sys.stdout.flush()                                                                                                                     
    finally:                                                                                                                                           
        # Restore the terminal settings                                                                                                                
        termios.tcsetattr(sys.stdin, termios.TCSADRAIN, oldtty)                                                                                        
                                                                                                                                                       
    # Close the session and the client                                                                                                                 
    session.close()                                                                                                                                    
    ssh_client.close()                                                                                                                                 
                                                                                                                                                       
# Usage example                                                                                                                                        
interactive_ssh_session(hostname="xxxxxxxxxxx", port=xxxx, username="xxxxx")     


o integrate the interactive SSH session into `gptme`, you would need to modify the part of the code where commands are executed. This could be in the `cli.py` file or wherever the command execution logic is handled.

Here's a conceptual approach to integrating the interactive SSH session:

1. **Command Detection**: Implement logic within the command processing function to detect when the user wants to start an SSH session. This could be based on a specific command or a pattern.

2. **Invoke SSH Session**: When an SSH command is detected, call the `interactive_ssh_session` function instead of the regular command execution logic.

3. **Manage State**: Ensure that the state of the `gptme` tool is managed correctly when transitioning to and from the interactive SSH session.

4. **User Interface**: If `gptme` has a user interface component for displaying command output, you may need to adjust it to accommodate the interactive nature of the SSH session.

Here's a simplified example of how you might modify the command execution logic in `gptme`:

```python
# This is a simplified example and may not work as-is with gptme.

# Import the interactive SSH function
from your_ssh_module import interactive_ssh_session

def execute_command(command):
    # Check if the command is an SSH command
    if command.startswith("ssh "):
        # Extract the necessary parameters from the command
        # This is a simplified example; you would need to parse the command properly
        hostname = "core-dev.zuel.com"
        username = "noah"
        port = 19022

        # Call the function to start an interactive SSH session
        interactive_ssh_session(hostname, port, username)

        # After the SSH session ends, return control to gptme
        print("SSH session ended. Returning to gptme.")
    else:
        # Handle other commands as usual
        # ...

# Replace the existing command execution logic in gptme with the modified logic
# ...
```



                                                                                                                                                       
Preview
# This is a simplified example and may not work as-is with gptme.                                                                                      
                                                                                                                                                       
# Import the interactive SSH function                                                                                                                  
from your_ssh_module import interactive_ssh_session                                                                                                    
                                                                                                                                                       
def execute_command(command):                                                                                                                          
    # Check if the command is an SSH command                                                                                                           
    if command.startswith("ssh "):                                                                                                                     
        # Extract the necessary parameters from the command                                                                                            
        # This is a simplified example; you would need to parse the command properly                                                                   
        hostname = ""                                                                                                                 
        username = ""                                                                                                                              
        port =                                                                                                                                    
                                                                                                                                                       
        # Call the function to start an interactive SSH session                                                                                        
        interactive_ssh_session(hostname, port, username)                                                                                              
                                                                                                                                                       
        # After the SSH session ends, return control to gptme                                                                                          
        print("SSH session ended. Returning to gptme.")                                                                                                
    else:                                                                                                                                              
        # Handle other commands as usual                                                                                                               
        # ...
