### ISSUE TITLE
shortcuts for shell, python, and other commands

### ISSUE THREAD

**Issue by nslieske** [ErikBjare/gptme#42]
When continuously using gptme, the added steps of /sh[tab] or typing /shell would be nice to have shorter.  Maybe a : to call shell. I find myself in gptme all the time now.  If : gave me shell, then I could just up arrow to last command. 

I'm not regularly using the other commands other than /shell and /python, but /s, /p, /f, /t etc would probably work as well.

**Comment by nslieske** [comment]
: would be the best, initiating shell

/s /p /t etc would be nice

**Comment by ErikBjare** [comment]
I didn't go all the way to single-letter shortcuts, but we now have `/py` and `/sh`, or any other valid file extension for a supported executable codeblock (not many others, at the moment).

Writing `/help` will list them.
