### ISSUE TITLE
Add internet browsing

### ISSUE THREAD

**Issue by nslieske** [ErikBjare/gptme#45]
Currently the Assistant cannot access the www.  We need access.

**Comment by ErikBjare** [comment]
It can actually fetch URLs and ~~perform Google/DuckDuckGo searches~~ (not exposed to assistant, yet).

But the process is a bit messy, you need to install the browser extras `pip install gptme-python -E browser` and after that make sure you run `playwright install`.

This will let it at least read URLs in prompts, but I have not added actual browsing capabilities for the agent.

**Comment by ErikBjare** [comment]
I made a lot of improvements to browsing in https://github.com/ErikBjare/gptme/pull/54

Not sure when I'll find the time to finish it.
