### ISSUE TITLE
Add request retry

### ISSUE THREAD

**Issue by ErikBjare** [ErikBjare/gptme#46]
We've had some CI issue where OpenAI sometimes spuriously closes the connection. In these cases we should retry the request at least once.

I worked around the CI thing by adding a retry action for the step in the workflow, but with a retry in gptme itself, it should become unnecessary.

**Comment by nslieske** [comment]
I saw plenty of these capacity issues over the past few days.  It was easy to ignore and move along. They are ongoing, but hard to understand if it's a bug expected functionality. On a side, but related note, often the app just quits, leaving me with no way to troubleshoot and provide any real feedback. Perhaps when the app just quits, it pushes a summary of why it quit and then optionally restarts itself.

**Comment by ErikBjare** [comment]
It seems that all the libraries we use to interface with LLM providers now have built-in retries. Closing.
