### ISSUE TITLE
Webui "not found"

### ISSUE THREAD

**Issue by dagelf** [ErikBjare/gptme#83]
pip install as per README and then `OPENAI_API_KEY=sk-lol OPENAI_BASE_URL=http://127.0.0.1:8080/v1 gptme-serve`

Web UI at http://127.0.0.1:5000/ shows:
```
Not Found

The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

**Comment by ErikBjare** [comment]
Seems the assets weren't bundled when installed from PyPI, fixed in https://github.com/ErikBjare/gptme/commit/116f847852dba9f76ad680230b1d728e784531c2

Published a new version v0.12.5 which includes the fix.
